server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;  # 모든 요청을 index.html로 보냄
    }

    # 백엔드 API로 요청을 보낼 때 (Proxy 설정)
    location /api/ {
        proxy_pass http://backend:8080/;  # 도커 네트워크의 backend 서비스로 전달
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}