name: Deploy

on:
  push:
    branches: [ "main", "gwon" ] # 사용하는 브랜치명 확인

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: react-frontend
    steps:
      # v3 대신 v4를 사용하여 Node.js 경고 해결
      - name: Checkout
        uses: actions/checkout@v4

      # 도커 로그인 (여기가 실패한다면 Secrets 오타 확인)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 이미지 빌드 및 푸시
      - name: Build and Push
        run: |
          # BUILD_MODE="production" 으로 명시적으로 묶어줍니다.
          docker build --build-arg BUILD_MODE="production" -t ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest